Repository TWOGATH3R/twogather-web-backend, pull requests merged in 2023-06, with the labels that each got.

#62 Twogather web backend 44
  src/docs/asciidoc/index.adoc
  src/main/java/com/twogather/twogatherwebbackend/auth/AuthMessage.java
  src/main/java/com/twogather/twogatherwebbackend/auth/JwtAccessDeniedHandler.java
  src/main/java/com/twogather/twogatherwebbackend/auth/JwtAuthenticationEntryPoint.java
  src/main/java/com/twogather/twogatherwebbackend/auth/JwtAuthenticationFilter.java
  src/main/java/com/twogather/twogatherwebbackend/auth/JwtAuthorizationFilter.java
  src/main/java/com/twogather/twogatherwebbackend/config/SecurityConfig.java
  src/main/java/com/twogather/twogatherwebbackend/controller/ConsumerController.java
  src/main/java/com/twogather/twogatherwebbackend/controller/ControllerAdvice.java
  src/main/java/com/twogather/twogatherwebbackend/controller/MemberController.java
  src/main/java/com/twogather/twogatherwebbackend/controller/StoreOwnerController.java
  src/main/java/com/twogather/twogatherwebbackend/domain/Member.java
  src/main/java/com/twogather/twogatherwebbackend/dto/PagedResponse.java
  src/main/java/com/twogather/twogatherwebbackend/dto/member/FindUsernameRequest.java
  src/main/java/com/twogather/twogatherwebbackend/dto/member/MemberSaveRequest.java
  src/main/java/com/twogather/twogatherwebbackend/dto/member/MemberUpdateRequest.java
  src/main/java/com/twogather/twogatherwebbackend/dto/member/PasswordRequest.java
  src/main/java/com/twogather/twogatherwebbackend/exception/CustomAccessDeniedException.java
  src/main/java/com/twogather/twogatherwebbackend/exception/CustomAuthenticationException.java
  src/main/java/com/twogather/twogatherwebbackend/exception/MemberException.java
  src/main/java/com/twogather/twogatherwebbackend/repository/ConsumerRepository.java
  src/main/java/com/twogather/twogatherwebbackend/repository/MemberRepository.java
  src/main/java/com/twogather/twogatherwebbackend/repository/StoreOwnerRepository.java
  src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepositoryImpl.java
  src/main/java/com/twogather/twogatherwebbackend/service/CommentService.java
  src/main/java/com/twogather/twogatherwebbackend/service/ConsumerService.java
  src/main/java/com/twogather/twogatherwebbackend/service/LikeService.java
  src/main/java/com/twogather/twogatherwebbackend/service/MemberService.java
  src/main/java/com/twogather/twogatherwebbackend/service/StoreOwnerService.java
  src/main/java/com/twogather/twogatherwebbackend/service/StoreService.java
  src/main/java/com/twogather/twogatherwebbackend/util/SecurityUtils.java
  src/main/resources/static/docs/index.html
  src/test/java/com/twogather/twogatherwebbackend/acceptance/AcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/AdminAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/BusinessHourAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/CategoryAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/JwtAuthorizationFilterTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/LikeAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/LoginAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/MemberAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/StoreExcludeGetAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/StoreGetAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/AdminControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/ConsumerControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/ControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/LoginTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/MemberControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/StoreOwnerControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/docs/DocumentFormatGenerator.java
  src/test/java/com/twogather/twogatherwebbackend/service/ConsumerServiceTest.java
  src/test/java/com/twogather/twogatherwebbackend/service/StoreOwnerServiceTest.java
  src/test/java/com/twogather/twogatherwebbackend/util/TestConstants.java
  src/test/java/com/twogather/twogatherwebbackend/util/TestUtil.java
Labels: docs, feature, refactoring, discussion

#65 Twogather web backend 64
  src/main/java/com/twogather/twogatherwebbackend/config/SecurityConfig.java
  src/main/java/com/twogather/twogatherwebbackend/controller/EmailController.java
  src/main/java/com/twogather/twogatherwebbackend/controller/MemberController.java
  src/main/java/com/twogather/twogatherwebbackend/service/EmailService.java
  src/main/java/com/twogather/twogatherwebbackend/service/MemberService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/twogather/twogatherwebbackend/acceptance/AcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/MemberAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/StoreExcludeGetAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/StoreGetAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/MemberControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/service/StoreOwnerServiceTest.java
Labels: bug

#67 Twogather web backend 66
  .gitignore
  src/docs/asciidoc/index.adoc
  src/main/java/com/twogather/twogatherwebbackend/controller/ControllerAdvice.java
  src/main/java/com/twogather/twogatherwebbackend/controller/MemberController.java
  src/main/java/com/twogather/twogatherwebbackend/domain/Image.java
  src/main/java/com/twogather/twogatherwebbackend/domain/Likes.java
  src/main/java/com/twogather/twogatherwebbackend/domain/Store.java
  src/main/java/com/twogather/twogatherwebbackend/domain/StoreKeyword.java
  src/main/java/com/twogather/twogatherwebbackend/dto/store/MyLikeStoreResponse.java
  src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepository.java
  src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepositoryImpl.java
  src/main/java/com/twogather/twogatherwebbackend/service/StoreService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/twogather/twogatherwebbackend/controller/MemberControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/StoreControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/repository/StoreRepositoryTest.java
Labels: docs, feature

#69 Twogather web backend 68
  src/main/java/com/twogather/twogatherwebbackend/controller/ReviewController.java
  src/main/java/com/twogather/twogatherwebbackend/controller/StoreController.java
  src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepository.java
  src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepositoryImpl.java
  src/main/java/com/twogather/twogatherwebbackend/service/ReviewService.java
  src/main/java/com/twogather/twogatherwebbackend/service/StoreService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/twogather/twogatherwebbackend/controller/MemberControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/ReviewControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/StoreControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/docs/DocumentFormatGenerator.java
  src/test/java/com/twogather/twogatherwebbackend/repository/StoreRepositoryTest.java
  src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
Labels: feature

#71 Twogather web backend 70
  src/docs/asciidoc/index.adoc
  src/main/java/com/twogather/twogatherwebbackend/dto/businesshour/BusinessHourResponse.java
  src/main/resources/static/docs/index.html
  src/test/java/com/twogather/twogatherwebbackend/controller/BusinessHourControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/LikeControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/MemberControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/util/TestConstants.java
  src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
Labels: docs, refactoring

#77 좋아요 개수 추가하기
  src/main/java/com/twogather/twogatherwebbackend/dto/store/StoreDefaultResponse.java
  src/main/java/com/twogather/twogatherwebbackend/dto/store/StoreResponseWithKeyword.java
  src/main/java/com/twogather/twogatherwebbackend/dto/store/TopStoreResponse.java
  src/main/java/com/twogather/twogatherwebbackend/exception/MemberException.java
  src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepositoryImpl.java
  src/main/resources/static/docs/index.html
  src/test/java/com/twogather/twogatherwebbackend/acceptance/AcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/AdminAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/CommentAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/ImageAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/MemberAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/StoreControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/repository/StoreRepositoryTest.java
  src/test/java/com/twogather/twogatherwebbackend/util/TestConstants.java
Labels: feature

#80 임시 비밀번호 전송 기능/이미지 전송 버그
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/twogather/twogatherwebbackend/config/SecurityConfig.java
  src/main/java/com/twogather/twogatherwebbackend/controller/EmailController.java
  src/main/java/com/twogather/twogatherwebbackend/controller/MemberController.java
  src/main/java/com/twogather/twogatherwebbackend/dto/member/FindPasswordRequest.java
  src/main/java/com/twogather/twogatherwebbackend/exception/EmailException.java
  src/main/java/com/twogather/twogatherwebbackend/exception/FileException.java
  src/main/java/com/twogather/twogatherwebbackend/exception/MemberException.java
  src/main/java/com/twogather/twogatherwebbackend/repository/MemberRepository.java
  src/main/java/com/twogather/twogatherwebbackend/service/EmailService.java
  src/main/java/com/twogather/twogatherwebbackend/service/MemberService.java
  src/main/java/com/twogather/twogatherwebbackend/service/S3Uploader.java
  src/main/java/com/twogather/twogatherwebbackend/util/PasswordGenerator.java
  src/main/resources/logback.xml
  src/main/resources/static/docs/index.html
  src/test/java/com/twogather/twogatherwebbackend/controller/EmailControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/util/TestConstants.java
Labels: bug, feature

#83 가게 응답 변경
  src/docs/asciidoc/index.adoc
  src/main/java/com/twogather/twogatherwebbackend/controller/StoreController.java
  src/main/java/com/twogather/twogatherwebbackend/dto/store/StoreSaveUpdateResponse.java
  src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepository.java
  src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepositoryImpl.java
  src/main/java/com/twogather/twogatherwebbackend/service/S3Uploader.java
  src/main/java/com/twogather/twogatherwebbackend/service/StoreService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/twogather/twogatherwebbackend/acceptance/AcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/StoreExcludeGetAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/StoreControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/util/TestConstants.java
Labels: feature

#22 리뷰 개발
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/twogather/twogatherwebbackend/controller/ControllerAdvice.java
  src/main/java/com/twogather/twogatherwebbackend/controller/ReviewController.java
  src/main/java/com/twogather/twogatherwebbackend/domain/BusinessHour.java
  src/main/java/com/twogather/twogatherwebbackend/domain/Member.java
  src/main/java/com/twogather/twogatherwebbackend/domain/Review.java
  src/main/java/com/twogather/twogatherwebbackend/dto/ErrorResponse.java
  src/main/java/com/twogather/twogatherwebbackend/dto/review/MyReviewInfoResponse.java
  src/main/java/com/twogather/twogatherwebbackend/dto/review/ReviewResponse.java
  src/main/java/com/twogather/twogatherwebbackend/dto/review/ReviewSaveRequest.java
  src/main/java/com/twogather/twogatherwebbackend/dto/review/ReviewSaveUpdateRequest.java
  src/main/java/com/twogather/twogatherwebbackend/dto/review/StoreDetailReviewResponse.java
  src/main/java/com/twogather/twogatherwebbackend/exception/BusinessHourException.java
  src/main/java/com/twogather/twogatherwebbackend/exception/CommentException.java
  src/main/java/com/twogather/twogatherwebbackend/exception/KeywordException.java
  src/main/java/com/twogather/twogatherwebbackend/exception/LikeException.java
  src/main/java/com/twogather/twogatherwebbackend/exception/ReviewException.java
  src/main/java/com/twogather/twogatherwebbackend/exception/StoreException.java
  src/main/java/com/twogather/twogatherwebbackend/repository/ConsumerRepository.java
  src/main/java/com/twogather/twogatherwebbackend/repository/review/ReviewCustomRepository.java
  src/main/java/com/twogather/twogatherwebbackend/repository/review/ReviewCustomRepositoryImpl.java
  src/main/java/com/twogather/twogatherwebbackend/repository/review/ReviewRepository.java
  src/main/java/com/twogather/twogatherwebbackend/service/BusinessHourService.java
  src/main/java/com/twogather/twogatherwebbackend/service/ReviewService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/twogather/twogatherwebbackend/acceptance/AcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/AdminAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/BusinessHourAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/CategoryAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/ImageAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/KeywordAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/LikeAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/MenuAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/acceptance/StoreExcludeGetAcceptanceTest.java
  src/test/java/com/twogather/twogatherwebbackend/config/EmbeddedS3Config.java
  src/test/java/com/twogather/twogatherwebbackend/controller/ReviewControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/docs/DocumentFormatGenerator.java
  src/test/java/com/twogather/twogatherwebbackend/repository/ReviewRepositoryTest.java
  src/test/java/com/twogather/twogatherwebbackend/util/TestConstants.java
  src/test/java/com/twogather/twogatherwebbackend/utils/ProcessUtils.java
Labels: feature, refactoring, test

#93 이미 승인된 가게 재요청 시 throw exception
  src/docs/asciidoc/index.adoc
  src/main/java/com/twogather/twogatherwebbackend/auth/JwtAuthorizationFilter.java
  src/main/java/com/twogather/twogatherwebbackend/controller/CommentController.java
  src/main/java/com/twogather/twogatherwebbackend/domain/Store.java
  src/main/java/com/twogather/twogatherwebbackend/dto/LoginResponse.java
  src/main/java/com/twogather/twogatherwebbackend/dto/comment/CommentResponse.java
  src/main/java/com/twogather/twogatherwebbackend/dto/store/StoreDefaultResponse.java
  src/main/java/com/twogather/twogatherwebbackend/exception/StoreException.java
  src/main/java/com/twogather/twogatherwebbackend/repository/store/StoreCustomRepositoryImpl.java
  src/main/java/com/twogather/twogatherwebbackend/service/CommentService.java
  src/main/resources/static/docs/index.html
  src/test/java/com/twogather/twogatherwebbackend/controller/CommentControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/LoginTest.java
  src/test/java/com/twogather/twogatherwebbackend/controller/StoreControllerTest.java
  src/test/java/com/twogather/twogatherwebbackend/util/TestConstants.java
Labels: feature
